export const MODEL = {
    CORE2CL: 'CORE2CL',
    CORE2CLPLUS: 'CORE2CLPLUS',
    CORE2CX: 'CORE2CX',
    CORE2CXPLUS: 'CORE2CXPLUS',
    CORE2SDI: 'CORE2SDI',
    COREGEV: 'COREGEV',
    CORENTSC: 'CORENTSC'
};

export const MODELS = Object.values(MODEL);