export const MODEL = {
    CORE2CL: 'CORE2CL',
    CORE2CLPLUS: 'CORE2CLPLUS',
    CORE2CLMAX: 'CORE2CLMAX',
    CORE2CX: 'CORE2CX',
    CORE2CXPLUS: 'CORE2CXPLUS',
    CORE2CXMAX: 'CORE2CXMAX',
    CORE2SDI: 'CORE2SDI',
    CORE2SDIMAX: 'CORE2SDIMAX',
    COREGEV: 'COREGEV',
    CORENTSC: 'CORENTSC'
};

export const MODELS = Object.values(MODEL);