import { MODEL } from './models';

export const RESOLUTION = {
  MAXIMUM: 'Maximum',
  R_4K: '4K (4096x2160)',
  UHD: 'UHD (3840x2160)',
  R_2K: '2K (2048x1080)',
  FHD: '1080p (1920x1080)',
  HD: '720p (1280x720)',
  VGA: 'VGA (640x480)',
  MINIMUM: 'Minimum',
  CUSTOM: 'Custom',
};

export const RESOLUTION_VALUES = {
  [RESOLUTION.MAXIMUM]: 'Maximum',
  [RESOLUTION.R_4K]: [4096, 2160],
  [RESOLUTION.UHD]: [3840, 2160],
  [RESOLUTION.R_2K]: [2048, 1080],
  [RESOLUTION.FHD]: [1920, 1080],
  [RESOLUTION.HD]: [1280, 720],
  [RESOLUTION.VGA]: [640, 480],
  [RESOLUTION.MINIMUM]: 'Minimum',
  [RESOLUTION.CUSTOM]: 'Custom',
};

export const RESOLUTIONS = Object.values(RESOLUTION);

export const NAN_RESOLUTIONS = [
  RESOLUTION.MINIMUM,
  RESOLUTION.MAXIMUM,
  RESOLUTION.CUSTOM,
];

export const MAX_RESOLUTIONS = {
  [MODEL.Type447X52MCX]: [8192, 5468],
  [MODEL.Type447X52CCX]: [8192, 5468],
  [MODEL.Type654G71MCX]: [9344, 7000],
  [MODEL.Type654G71CCX]: [9344, 7000],
};

export const RESOLUTION_PRESETS = {
  [MODEL.Type120C335MCX]: [
    RESOLUTION.MAXIMUM,
    RESOLUTION.R_4K,
    RESOLUTION.UHD,
    RESOLUTION.R_2K,
    RESOLUTION.FHD,
    RESOLUTION.HD,
    RESOLUTION.VGA,
    RESOLUTION.MINIMUM,
    RESOLUTION.CUSTOM,
  ],
  [MODEL.Type120C335CCX]: [
    RESOLUTION.MAXIMUM,
    RESOLUTION.R_4K,
    RESOLUTION.UHD,
    RESOLUTION.R_2K,
    RESOLUTION.FHD,
    RESOLUTION.HD,
    RESOLUTION.VGA,
    RESOLUTION.MINIMUM,
    RESOLUTION.CUSTOM,
  ],
  [MODEL.Type447X52MCX]: [
    RESOLUTION.MAXIMUM,
    RESOLUTION.R_4K,
    RESOLUTION.UHD,
    RESOLUTION.R_2K,
    RESOLUTION.FHD,
    RESOLUTION.HD,
    RESOLUTION.VGA,
    RESOLUTION.MINIMUM,
    RESOLUTION.CUSTOM,
  ],
  [MODEL.Type447X52CCX]: [
    RESOLUTION.MAXIMUM,
    RESOLUTION.R_4K,
    RESOLUTION.UHD,
    RESOLUTION.R_2K,
    RESOLUTION.FHD,
    RESOLUTION.HD,
    RESOLUTION.VGA,
    RESOLUTION.MINIMUM,
    RESOLUTION.CUSTOM,
  ],
  [MODEL.Type654G71MCX]: [
    RESOLUTION.MAXIMUM,
    RESOLUTION.R_4K,
    RESOLUTION.UHD,
    RESOLUTION.R_2K,
    RESOLUTION.FHD,
    RESOLUTION.HD,
    RESOLUTION.VGA,
    RESOLUTION.MINIMUM,
    RESOLUTION.CUSTOM,
  ],
  [MODEL.Type654G71CCX]: [
    RESOLUTION.MAXIMUM,
    RESOLUTION.R_4K,
    RESOLUTION.UHD,
    RESOLUTION.R_2K,
    RESOLUTION.FHD,
    RESOLUTION.HD,
    RESOLUTION.VGA,
    RESOLUTION.MINIMUM,
    RESOLUTION.CUSTOM,
  ],
};
